- builtin/app/node/customization.go
> app/node: fix node_version interpolation

- website/source/docs/concepts/deps.html.md
The link did not lead to anywhere and I'm guessing this is the proper
destination.
> Fix dependency sources link

- website/source/intro/getting-started/build.html.md
> Fix typo in the word "tighter" on the build page of the website

- appfile/validate.go
> Typo in Appfile validation.

- Vagrantfile
Fixes the Box name issue #108 while doing Vagrant up https://github.com/hashicorp/otto/issues/108
> Box name issue #108

- images/README.md
> fixes a small typo

- commands.go
- commands_test.go
Fixes issues where package.json exists in a Ruby or PHP project
- Fixes #127
- Fixes #128
> Prioritize Ruby/PHP detection over Node

- command/compile.go
- website/source/docs/commands/compile.html.md.erb
Signed-off-by: LaurentCrisci <laurent.crisci@itv.com>
> Fixed typo in compile command/doc

- app/mock.go
- command/compile.go
- command/compile_test.go
- foundation/mock.go
- otto/testing.go
> command/compile: Fix implicit app name from dir

- appfile/file.go
- appfile/file_test.go
Fixes #192 
This makes the application more granular so that the type can be omitted from the Appfile.
> appfile: merge application more granular [GH-192]

- website/source/docs/concepts/deps.html.md
"so dependency sources" -> "to dependency sources"
> Fix typo in deps.html

- website/source/docs/concepts/deps.html.md
> Fix small typo

- helper/vagrant/vagrant.go
Fixes #256 
This sets `VAGRANT_CWD` directly so that parent env vars don't poison it.
/cc @phinze: Also a way cleaner way to do env vars
> helper/vagrant: set cwd explicitly [GH-256]

- command/build.go
> commands/build: Show usage if passed args

- command/plugin_manager.go
This special cases built-in plugins when they are stored so that we aren't storing the absolute path to Otto itself. This makes plugin loading a bit more robust for if the Otto binary is moved around.
> command/plugin-manager: built-in plugins are special-cased

- website/source/intro/vs/heroku.html.md
I don't think admittingly is correct.
> Change admittingly to admittedly

- appfile/detect/parse.go
- appfile/parse.go
**DO NOT MERGE YET: Upstream HCL isn't updated yet, this is just staging the changes.**
This updates the HCL parsers to the new API. The tests are unchanged and verify the functionality.
> Use new HCL API

- builtin/foundation/consul/data/common/app-build/main.sh.tpl
- builtin/foundation/consul/data/common/app-dev/layer.sh.tpl
- builtin/foundation/consul/data/common/app-dev/main.sh.tpl
- helper/hashitools/installer_go.go
- helper/hashitools/installer_vagrant.go
- images/foundation-consul/scripts/ubuntu/install.sh
- images/scripts/common/consul.sh
> Move to HashiCorp releases API for installers

- website/source/docs/appfile/project.html.md
> docs/appfile: Clarify name of project infra

- builtin/app/docker-external/data/common/dev-dep/Vagrantfile.fragment.tpl
> Update Apt cache before installing HTTPS transport

- examples/ruby/README.md
`app.rb` and `config.ru` is clearly a Sinatra app, not a Middleman app
> change Middleman into Sinatra

- website/source/intro/getting-started/deps.html.md
While following otto's tutorial I found a small missing step (at least a think so).
> changes on Appfile requires `otto compile`

- website/source/intro/getting-started/appfile.html.md
> Quick Spelling Fix

- command/compile.go
test plan:
* view the output of `bin/otto`
* verify periods are consistent :D
> remove period in help

- Makefile
"Reviewal" - sounds like something my synergy-oriented boss thought up to do in pairs over s'mores at the company retreat. Yikes!
> Fix wording typo

- builtin/app/python/data/aws-simple/build/build-python.sh.tpl
This is still a work in progress. The following still needs to be done before merging:
* Test with more frameworks (currently, only Flask has been tested)
* Validate python_version at compile time so a friendly error message can be presented instead of failing unexpectedly during "dev" or "build"
* Add documentation 
Feedback is welcome.
> Add python app support

- appfile/file.go
- appfile/file_hcl.go
- appfile/file_hcl_test.go
- appfile/file_test.go
- appfile/parse.go
- appfile/parse_test.go
- appfile/test-fixtures/app-version.golden
- appfile/test-fixtures/app-version.hcl
- appfile/test-fixtures/validate-app-bad-version/Appfile
- appfile/test-fixtures/validate-app-version/Appfile
- appfile/validate.go
- appfile/validate_test.go
This adds a `version` field to the `application` stanza. 
This will be documented later. Just laying the groundwork for other stuff coming.
> Adds version to Application

- website/source/layouts/_sidebar.erb
> Link to otto rather than terraform on Github

- helper/compile/data/app/dev/Vagrantfile-layer.tpl
- helper/compile/data/app/dev/Vagrantfile.tpl
> Fix hashicorp/otto#391
