website/source/docs/apps/node/customization.html.md

The current version referenced, 1.4.0 conflicts with the value found in `builtin/app/node/app.go`, 4.1.0

Update for Node customization documentation

---

appfile/compile_json.go
appfile/compile_test.go
appfile/test-fixtures/compile-multi-dep/Appfile
appfile/test-fixtures/compile-multi-dep/childone/Appfile
appfile/test-fixtures/compile-multi-dep/childtwo/Appfile

The JSON representation of the graph had a single object to represent
the set of edges - this meant that multiple edges with the same source
would clobber each other.
Change to a list of objects (one per edge) to avoid this collision.
fixes #72

appfile: fix issue marshalling multiple deps

---

command/compile.go

Since "name" parameter is required for "Application" section when compiling Appfile, it would be nice to have mention about that in "errCantDetectType" error message.

Include application name to "errCantDetectType" error message text

---

builtin/foundation/consul/data/common/app-build/main.sh.tpl

- Currently if you do an `otto dev destroy` followed by a
`otto dev` without a `otto compile` step inbetween it will
fail to properly install consul as a service again due to
the move of the upstart file.
Fixes #111

Making consul installation more idempotent

---

builtin/app/ruby/data/common/dev/Vagrantfile.tpl

This changes the provisioning script to not run as root. In or to do this, we set GEM_HOME to `$HOME/.gem` during the provision and for the *vagrant* user.
Prior to this, `bundle` would work, but `gem install` would result in permissions errors.

app/ruby: Deprivilege provisioning, fix GEM_HOME

---

command/compile.go
command/compile_test.go
command/meta.go
command/test-fixtures/compile-alt/appfile.hcl
command/test-fixtures/compile-dir/dir/Appfile

Adds logic so Otto will automatically recognize appfile.hcl in addition
to Appfile.
Fixes #61

command: support alternative Appfile name

---

command/compile.go

When running "make dev" getting "command/compile.go:221: undefined: path"
Think flag is the intended variable.

Fix undefined: path.

---

command/meta.go

The `otto compile` command can take a dir argument, but Core was
assuming it could use cwd in RootDir() to look for the `.otto`
directory. This moves the wd assumption out of RootDir and up in to
Appfile(), which is used by the other non-compile commands.
Should fix the build.

appfile: fix non-cwd compile

---

otto/core.go

This output the type not being supported when that is the case.

Clarify error message when infrastructure type not supported.

---

helper/hashitools/project.go
helper/hashitools/project_test.go
helper/hashitools/test-fixtures/vagrant-version-stderr/vagrant

fixes #70
I did a quick sweep of all our tools, and they all print version to
stdout, so ignoring stderr should be AOK.

helper/hashitools: ignore stderr when checking version

---

builtin/app/ruby/data/common/dev/Vagrantfile.tpl

Greps for gem names in Gemfile.lock, or Gemfile if a lockfile does not exist.
For each found gem, installs system dependencies for that gem using apt.
This could be optimized in the future to build up a complete list of dependencies to install, and running `apt-get` once.
Alternative to #132
Fixes #104
Fixes #133

app/ruby: Detect gem deps for apt-get

---

builtin/app/ruby/data/common/dev/Vagrantfile.tpl

Does a `bundle ` (install) during `otto dev`. This is semi-dependent on #137, since ideally `otto dev` would not fail due to an error compiling native gems.
Fixes #150

app/ruby: Bundle during otto dev

---

builtin/app/node/data/common/dev/Vagrantfile.tpl

Per #126 , adding git package install in `nodejs` default `Vagrantfile`

adding git to default nodejs Vagrantfile provisioning

---

builtin/app/ruby/data/common/dev/Vagrantfile.tpl

Default the bash array to return empty
Introduced in #137
Fixes #181

app/ruby: Fix unbound var error

---

builtin/app/ruby/data/common/dev/Vagrantfile.tpl

My app was failing to build because `libxml-ruby` required the `libxml-dev` package. As per #133 , this seems to be the preferred way to require packages for now?

Install libxml dependancy for libxml-ruby

---

helper/vagrant/dev.go

Adds `otto dev halt` as a shortcut for `otto dev vagrant halt`.
With existing dev env:
```
$ otto dev halt
==> Halting the the local development environment...
==> default: Attempting graceful shutdown of VM...
==> Development environment halted!
```
Without having run `otto dev`:
```
$ otto dev halt
==> Halting the the local development environment...
==> default: VM not created. Moving on...
==> Development environment halted!
```
Help output:
```
$ otto dev help
The available subcommands are shown below along with a
brief description of what that command does. For more complete
help, call the `help` subcommand with the name of the specific
subcommand you want help for, such as `help foo`.
The subcommand '(default)' is the blank subcommand. For this
you don't specify any additional …
```

helper/vagrant: Add halt action

---

command/compile.go
command/compile_test.go
command/test-fixtures/compile-detection/Appfile

@mitchellh Fixes #192 is still not functional due to an issue with the parameters being passed into the default method. 
- Adjusting the output of the loadAppfile method to properly
return Appfile's dir instead of path

Adjusting appfile loading to allow for proper type merging

---

builtin/app/ruby/data/common/dev/Vagrantfile.tpl
builtin/app/ruby/tuple.go
commands.go
commands_test.go
helper/compile/app.go

This adds a Rails type to the detectors, and exposes this as app_type to the templates. If Rails is detected, we prepare/migrate the database. If the pg gem is present, we install PostgreSQL 9.1. Sqlite is also implicitly supported.
This does not add MySQL support.

app/ruby: Rails w/ Postgres/Sqlite support

---

website/source/docs/apps/custom/customization.html.md
website/source/docs/apps/docker-external/customization.html.md
website/source/docs/apps/go/customization.html.md
website/source/docs/apps/node/customization.html.md
website/source/docs/apps/php/customization.html.md
website/source/docs/apps/ruby/customization.html.md
website/source/docs/infra/index.html.md

- Replace all occurrences of '[aA]vailabile' with '[aA]vailable]'
- Replace occurrence of 'infrastrctrue' with 'infrastructure'

docs: fix common typos

---

builtin/app/node/data/aws-simple/build/build-node.sh.tpl

Fixes #214 by making the "devDependencies" available during the various npm script targets prior to cleaning them up with the npm prune --production.

Customizing node installation to allow for preprocessing

---

builtin/app/ruby/data/common/dev/Vagrantfile.tpl

The [paperclip](https://github.com/thoughtbot/paperclip) gem relies on the `imagemagick` package for it's image processing and not on `rmagick`.  Pull request #133 suggests adding submitting pull requests to handle package specific binaries.  Is this still the case or have I missed a way to easily configure specific packages?

Add imagemagick dependency for paperclip

---

builtin/app/custom/customization.go

For the custom app type, render Vagrantfile as-is when compiling for development.
[Fixes: #158]

Custom type vagranfile rendering

---

command/help.go
commands.go
main.go

Fixes #74 
This adds a stub `otto help` command that shows how to get help for Otto commands (since we don't use that subcommand). This is to help people expecting this to work. 
We filter the `otto` output so that the help subcommand isn't shown. It is just there in case someone types it.

command/help 

---

app/app.go
infrastructure/infrastructure.go
otto/compile.go
otto/core.go
otto/core_test.go
otto/otto_test.go
otto/test-fixtures/basic/.ottoid
otto/testing.go

This adds a field to `CompileResult` that apps can use to store an arbitrary version. This version can be accessed in the context in the future to do version-specific behavior. 
This should let us change the app implementation but understand compilation directories from a previous version.

Apps can return/access "compile version"

---

command/meta.go
command/plugin_manager.go

This adds plugin discovery for external plugins. The original PR only added built-in plugin loading.

command/plugin-manager: discover external plugins

---

command/plugin_manager.go
helper/vagrant/ssh.go
plugin/client.go
plugin/server.go
rpc/app_test.go
rpc/client.go
rpc/client_test.go
rpc/directory_test.go
rpc/rpc_test.go
rpc/server.go
rpc/stream.go

This makes it so that `os.Stdout` and `os.Stderr` work in plugins: if you write to them, they go to stdout/stderr on the host process. Plugins _should_ use `Ui` objects to communicate with the outside world but some situations such as `otto dev ssh` which subprocess to `ssh` require direct access to stdout/stderr/stdin.
It turns out we already hooked up stdin just fine with plugins, but stdout/stderr were being dropped. This makes it so that stdout/stderr are now streamed across yamux streams and mirrored directly onto the host version.

Plugin streams (stdout, stderr) are connected

---

builtin/app/ruby/data/common/dev/Vagrantfile.tpl

The [poltergeist](https://github.com/teampoltergeist/poltergeist) gem depends on ``phantomjs``. :ghost: 
Adding this to the Vagrantfile as described in #133.

app/ruby: Add apt deps for poltergeist

---

appfile/file_hcl.go
appfile/file_hcl_test.go
appfile/test-fixtures/basic.golden

This adds an `HCL` method to the `*appfile.File` which makes it usable with the HCL printer library in order to output HCL. Tests are included that show example output.

appfile: support writing Appfile to HCL

---

app/mock.go
app/mock_test.go
otto/closer.go
otto/core.go
otto/core_test.go

This makes it so the Core calls `Close` if any interface impl is an io.Closer. This cleans up plugins for us throughout the core.

otto: call Close if impl is io.Closer

---

builtin/app/ruby/data/common/dev/Vagrantfile.tpl

``libxml-dev`` is not a valid package. We need to install ``libxml2-dev``.
See #315.

app/ruby: Fix dependencies for libxml-ruby

---

helper/hashitools/installer_vagrant.go

With the changes from #353 I was seeing a `403`
```bash
...
==> Downloading Vagrant v1.7.4...
URL: https://releases.hashicorp.com/vagrant/vagrant_1.7.4/vagrant_1.7.4.dmg
Error building dev environment: Error downloading, status code 403
...
```
This fixes it.

Fix for 403 on OSX

---

helper/vagrant/ui.go
helper/vagrant/ui_test.go
helper/vagrant/vagrant.go

This modifies `helper/vagrant` to be more like Packer where it always uses machine-readable output. This will give us more flexibility in the future to more easily grab info we need as we get it. 
This makes no functional changes.

helper/vagrant: Use Vagrant machine readable output

---

helper/compile/data/app/dev/Vagrantfile-layer.tpl
helper/compile/data/app/dev/Vagrantfile.tpl

This PR enable "linked clone" feature for envs created with Parallels provider.
Option "linked_clone" is available in "vagrant-parallels" >=1.6.0, which we will release as soon as Vagrant 1.8.0 is released.
P.s. By the way, we will also support layered envs there (https://github.com/Parallels/vagrant-parallels/pull/224) :wink:

Enable linked clones for Vagrant Parallels provider

---

helper/vagrant/ssh.go

Fixes GH-343
This uses the machine-readable output stuff we just introduced as part of Vagrant 1.8 to capture only the pure SSH config.

helper/vagrant: use machine-readable output to capture SSH config

---

builtin/foundation/consul/data/common/app-dev/layer.sh.tpl
builtin/foundation/consul/data/common/app-dev/main.sh.tpl

Changesets:
- In app-build/main.sh.tpl; it correctly uses cp so can be run multiple times
- Only in app-dev/layer.sh.tpl and app-dev/layer.sh.tpl it uses mv
- This means; if otto destroy is invoked without re-running otto compile; it will fail
Before running 'otto dev'
```
compiled leow$ find . -name upstart.conf
./app/foundation-consul/app-build/upstart.conf
./app/foundation-consul/app-dev/upstart.conf
./dep-24cbbebc-fc41-53b4-c844-60d642fb523c/foundation-consul/app-build/upstart.conf
./dep-24cbbebc-fc41-53b4-c844-60d642fb523c/foundation-consul/app-dev/upstart.conf
./foundation-consul/app-build/upstart.conf
./foundation-consul/app-dev/upstart.conf
```
After running 'otto dev'; upstart,conf is missing as reported
```
compiled leow$ find . -name upstart.conf …
```

Summary: Fixes issue #352

---

builtin/app/node/app.go
builtin/app/node/data/aws-simple/build/template.json.tpl
builtin/app/php/app.go
builtin/app/php/data/aws-simple/build/template.json.tpl
builtin/app/ruby/app.go
builtin/app/ruby/data/aws-simple/build/template.json.tpl
builtin/app/ruby/data/aws-vpc-public-private/build/template.json.tpl

If a user deleted their default VPC then Packer would generate an error. Instead lets use the same vpc/subnet generated by `otto infra`.
Issue
#235

Packer: explicitly set vpc & subnet 

---

builtin/app/ruby/app.go
builtin/app/ruby/app_test.go
builtin/app/ruby/gemfile.go
builtin/app/ruby/gemfile_test.go
builtin/app/ruby/test-fixtures/hasgem-basic/Gemfile
builtin/app/ruby/test-fixtures/hasgem-empty/main.rb
builtin/app/ruby/test-fixtures/hasgem-lock-basic/Gemfile.lock
builtin/app/ruby/test-fixtures/implicit-none/Gemfile
builtin/app/ruby/test-fixtures/implicit-redis/Gemfile
examples/redis/.ottoid
examples/redis/Appfile

/cc @justincampbell 
This adds implicit support for Ruby. We inspect the local Gemfile for gems and use that to determine what dependencies to add to the environment.
We are starting with just Redis, but can add more later very very easily.

Ruby Implicit Dependencies

---

appfile/detect/config.go
appfile/detect/parse_test.go
appfile/detect/sort.go
appfile/detect/sort_test.go
appfile/detect/test-fixtures/parse/priority.hcl
builtin/app/node/meta.go
builtin/app/scriptpack/meta.go
command/compile.go
command/compile_test.go

This adds the ability to add a priority to detectors, allowing app types to control the order in which detection happens. This should be used VERY sparingly, but we needed it for a couple use cases:
* `scriptpack` should always beat `go`, it is a more specific version
* `ruby` should beat `node`, since some Ruby projects contain `package.json` for assets
I purposely didn't document this outside of code, it shouldn't need to be used except in special cases.

Detector priority levels

---

builtin/app/ruby/app.go

This adds implicit dependecies for starting Memcached/PostgreSQL Docker containers when the dalli/pg gems are detected.
Needs #386 for Memcached example Appfile

app/ruby: Implicit depdendencies for dalli/pg

---

website/source/docs/concepts/appfile.html.md

Simple change from affect -> effect.
Affect is _almost always_ the verb and effect is _almost always_ the noun. This is one of those cases.

Fix typo in appfile.html.md.
